---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-multiarch-openshift-io-v1beta1-clusterpodplacementconfig
  failurePolicy: Fail
  name: validate-clusterpodplacementconfig.multiarch.openshift.io
  rules:
  - apiGroups:
    - multiarch.openshift.io
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - clusterpodplacementconfigs
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-multiarch-openshift-io-v1beta1-podplacementconfig
  failurePolicy: Fail
  name: vpodplacementconfig.kb.io
  rules:
  - apiGroups:
    - multiarch.openshift.io
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - podplacementconfigs
  sideEffects: None
